# Dot product practical example, Nut Butter sales

In [3]:
import numpy as np
import pandas as pd

np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [4]:
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [6]:
butter_prices = pd.Series([450, 300, 420], index=["Almond butter",	"Peanut butter", "Cashew butter"])
butter_prices

Almond butter    450
Peanut butter    300
Cashew butter    420
dtype: int64

In [21]:
weekly_sales.iloc[2, 1]
butter_prices.get("Almond butter")
weekly_sales.columns[0]

'Almond butter'

In [23]:
daily_sales = []
temp_total = 0

for i in range(weekly_sales.index.size):
    for j in range(weekly_sales.columns.size):
        temp_total += weekly_sales.iloc[i, j] * butter_prices.get(weekly_sales.columns[j])
    daily_sales.append(temp_total)
    temp_total = 0

weekly_sales["Daily sales"] = daily_sales
weekly_sales

       Almond butter  Peanut butter  Cashew butter  Daily sales
Mon               12             15              0         9900
Tues               3              3              7         5190
Wed                9             19             18        17310
Thurs              4              6             12         8640
Fri                1              6              7         5190